// src/App.vue
<script lang="tsx" setup>
import { ref } from 'vue';
import Cc from './components/async/Cc';
import { useState, markRegularFunctionComponent, useContext, useRef, createJsxFunctionComponent } from 'vue-function-component';
import { C } from './components/context';

const B = ((props: { a: number }) => {
  const [count, setCount] = useState(1)
  console.log(useContext(C))
  return <>
    <h1>B - count - {count}</h1>
    <button onClick={() => setCount(count + 1)}>点击</button>
    <Ccc />
  </>
})

function Ccc() {
  const divRef = useRef()
  return <div ref={divRef}>
    {useContext(C)}
  </div>;
}

const A = markRegularFunctionComponent(() => {
  return (<>
    <h1>A</h1>
    {/* <Cc a={1} b={2}></Cc> */}
    <B a={1} />
    <C value={100}>
      <B a={1} />
    </C>
  </>)
})

const count = ref(1);

</script>

<template>
  <transition>
    <div>
      <A :a="count" :b="[1, 2, 3]" />
      <h1>{{ count }}</h1>
      <button @click="count++">点击</button>
    </div>
  </transition>
</template>

// src/app/react/src/App.tsx
import { useState, createContext, useContext } from "react";
import "./App.css";

const C = createContext(1);
console.log(C);
console.log(createContext)

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <C.Provider value={2 + count}>
          <C.Provider value={3 + count}>
            <C.Consumer>{Cc}</C.Consumer>
            <B></B>
          </C.Provider>
          <B></B>
        </C.Provider>
      </div>
    </>
  );
}

function B() {
  const value = useContext(C);
  return <h1>b - {value}</h1>;
}

function Cc(value) {
  return (
    <>
      <h1>Cc - {value}</h1>
      <B />
    </>
  );
}

export default App;
